version: "3.9"

services:
  vagtplan:
    build: .
    container_name: vagtplan_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - PHP_ENV=development
    restart: unless-stopped
